"""add durable room invitations and share links

Revision ID: 20260712_room_invites
Revises: 20260711_ai_trails
Create Date: 2026-07-12
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260712_room_invites"
down_revision: Union[str, None] = (
    "20260711_ai_trails"
)
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    op.create_table(
        "room_invitations",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "room_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "invited_by_user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "invited_email",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=30),
            nullable=False,
            server_default="member",
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "accepted_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "declined_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["study_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_hash",
            name=(
                "uq_room_invitations_"
                "token_hash"
            ),
        ),
    )

    op.create_index(
        "ix_room_invitations_id",
        "room_invitations",
        ["id"],
    )
    op.create_index(
        "ix_room_invitations_room_id",
        "room_invitations",
        ["room_id"],
    )
    op.create_index(
        "ix_room_invitations_invited_by",
        "room_invitations",
        ["invited_by_user_id"],
    )
    op.create_index(
        "ix_room_invitations_email",
        "room_invitations",
        ["invited_email"],
    )
    op.create_index(
        "ix_room_invitations_token_hash",
        "room_invitations",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_room_invitations_status",
        "room_invitations",
        ["status"],
    )
    op.create_index(
        "ix_room_invitations_expires_at",
        "room_invitations",
        ["expires_at"],
    )
    op.create_index(
        "ix_room_invitations_accepted_by",
        "room_invitations",
        ["accepted_by_user_id"],
    )

    op.create_table(
        "room_invite_links",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "room_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=30),
            nullable=False,
            server_default="member",
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "max_uses",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "use_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["study_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_hash",
            name=(
                "uq_room_invite_links_"
                "token_hash"
            ),
        ),
    )

    op.create_index(
        "ix_room_invite_links_id",
        "room_invite_links",
        ["id"],
    )
    op.create_index(
        "ix_room_invite_links_room_id",
        "room_invite_links",
        ["room_id"],
    )
    op.create_index(
        "ix_room_invite_links_created_by",
        "room_invite_links",
        ["created_by_user_id"],
    )
    op.create_index(
        "ix_room_invite_links_token_hash",
        "room_invite_links",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_room_invite_links_status",
        "room_invite_links",
        ["status"],
    )
    op.create_index(
        "ix_room_invite_links_expires_at",
        "room_invite_links",
        ["expires_at"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_room_invite_links_expires_at",
        table_name="room_invite_links",
    )
    op.drop_index(
        "ix_room_invite_links_status",
        table_name="room_invite_links",
    )
    op.drop_index(
        "ix_room_invite_links_token_hash",
        table_name="room_invite_links",
    )
    op.drop_index(
        "ix_room_invite_links_created_by",
        table_name="room_invite_links",
    )
    op.drop_index(
        "ix_room_invite_links_room_id",
        table_name="room_invite_links",
    )
    op.drop_index(
        "ix_room_invite_links_id",
        table_name="room_invite_links",
    )
    op.drop_table("room_invite_links")

    op.drop_index(
        "ix_room_invitations_accepted_by",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_expires_at",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_status",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_token_hash",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_email",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_invited_by",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_room_id",
        table_name="room_invitations",
    )
    op.drop_index(
        "ix_room_invitations_id",
        table_name="room_invitations",
    )
    op.drop_table("room_invitations")
